### ISSUE TITLE
[Bug] Android ID 偽装をONにすると、二回目以降の起動ができなくなります。

### ISSUE THREAD

**Issue by Kabaki025** [Chipppppppppp/LIME#82]
### 内容の詳細

Android ID を偽装にチェックを入れ全て設定し終えた後、アプリを再起動するとそれ以降起動できなくなります。
チェックを入れずにログインすると、二回目以降も正常に起動します

クラッシュログ:
```
time: 1708950088041
msg: javax.crypto.BadPaddingException: pad block corrupted
stacktrace: java.lang.RuntimeException: Unable to create application jp.naver.line.android.LineApplication: java.lang.RuntimeException: decrypt error
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6811)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7914)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.RuntimeException: decrypt error
	at jp.naver.line.android.util.n.a(Unknown Source:47)
	at dj1.d.b(Unknown Source:74)
	at ej1.a.C(Unknown Source:13)
	at uj5.b.f(Unknown Source:27)
	at f0.a0.run(Unknown Source:73)
	at f0.r3.run(Unknown Source:679)
	at com.google.android.gms.internal.ads.ug.d(Unknown Source:52)
	at rj5.g.a(Unknown Source:32)
	at jp.naver.line.android.LineApplication.onCreate(Unknown Source:1504)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1287)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6806)
	... 9 more
Caused by: javax.crypto.BadPaddingException: pad block corrupted
	at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(BaseBlockCipher.java:1449)
	at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1274)
	at javax.crypto.Cipher.doFinal(Cipher.java:2056)
	at jp.naver.line.android.util.n.a(Unknown Source:31)
	... 19 more

```

Moto g52j 5G、Xperia XZ1、どちらもAndroid 13で検証しています。
https://github.com/Chipppppppppp/LIME/assets/62600076/312a89a5-dda8-4a76-9fdf-5ad32be62e3c

### 再現する手順

1. アプリ起動
2. Android ID を偽装をタップした後、ログイン
3. その他の方法でログイン
4. 電話番号でログイン
5. トーク履歴を復元＆バックアップPIN入力
6. 友だち追加設定無し
7. 年齢確認: あとで
8. 通知とバッテリー設定
9. タスクキル
10. 起動

### モジュールのバージョン

1.7.0

### LINEアプリのバージョン

14.2.0

**Comment by Kabaki025** [comment]
返信遅れてしまい申し訳ございません。
あの後検証したところ無事正常に動作しました。ありがとうございます(*  ˊ꒳ˋ*)

**Comment by Chipppppppppp** [comment]
よかったです
